/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('./src/components/Icon/src/Icon.vue')['default']
    NewPopup: typeof import('./src/components/NewPopup/src/NewPopup.vue')['default']
    RecordTable: typeof import('./src/components/RecordTable/src/RecordTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
